title: Slothful CRUD
description: A library designed to streamline the creation of CRUD endpoints effortlessly. Implementing the necessary interfaces in domain classes allows you to quickly register the library and generate RESTful endpoints.
baseurl: ""
url: "https://slothful.dev"
repository: dfyda/slothful-crud
theme: just-the-docs

#logo: "/assets/slothful-api.jpg"

aux_links:
  Repository: https://github.com/dfyda/slothful-crud

footer_content: "Copyright &copy; 2024 Damian Fyda. Distributed by an <a href=\"https://github.com/dfyda/slothful-crud/tree/main/LICENSE.txt\">MIT license.</a>"

color_scheme: dark

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# External navigation links
nav_external_links:
  - title: Slothful CRUD on GitHub
    url: https://github.com/dfyda/slothful-crud